denkungsart/filmmakers-api

source/index.html.md

Add examples for `imdb_id` to actor profile and talent agency snippets.

Include imdb_id in #show examples

---

source/index.html.md

Add new updated_at field to ActorProfiles#index

---

source/index.html.md

References https://github.com/denkungsart/castupload/issues/9035 and https://github.com/denkungsart/castupload/issues/9011
Changes:
- update index fields tables:
- `picture_copyright`
- `representative` of actor profile
- add `representative` to JSON example for show action

Update index section due to new fields

---

source/index.html.md

Related to https://github.com/denkungsart/filmmakers/issues/10127 and https://github.com/denkungsart/filmmakers/issues/10128 issues.
Corresponding PR: https://github.com/denkungsart/filmmakers/pull/10243

Update docs for `talent_agencies/:id` endpoint

---

source/index.html.md

Pagination section with information about per_page param

---

source/index.html.md

Document blog post filtering by tags

---

source/index.html.md

References https://github.com/denkungsart/filmmakers/issues/9711
- add explanations about new fields
- include examples in JSON
- add `professions` to deprecation section

Update API due to main_profession and specialization changes

---

source/index.html.md

References https://github.com/denkungsart/filmmakers/issues/11706
- add `in_development` to Vita JSON examples
- add changelog entry

Update docs due to new field VitaEntry#in_development

---

source/index.html.md

References https://github.com/denkungsart/filmmakers/issues/12405
* extend JSON example for new talent agency connection fields
* explain new fields in table
* add changelog entry

Update API docs for changes in talent agency connections

---

source/index.html.md

References https://github.com/denkungsart/filmmakers/issues/10211
- add `ethnic_background`, `ethnic_background_details` and `ethnic_background_custom` to response fields table
- add new attributes to JSON example
- add deprecation note about `ethnic_appearances`
- add changelog entry

Add documentation for new ethnicity attributes

---

README.md
source/index.html.md

Updates documentation for https://github.com/denkungsart/filmmakers/pull/12651

OAuth API Update

---

source/index.html.md

References https://github.com/denkungsart/filmmakers/issues/12596
- add `working_permits` to show view JSON example
- add changelog entry

Add working_permits to JSON example

---

source/index.html.md

References https://github.com/denkungsart/filmmakers/pull/12729
- describe `attribute_visibility.working_permits`

Add attribute visibility of working_permits

---

source/index.html.md

resolves GH-64
Created w/ o1 based on our controller spec for this endpoint

Document crew_profiles endpoint

---

source/index.html.md

References https://github.com/denkungsart/filmmakers/issues/13003
- add `about_me` to crew JSON example

Add about_me to crew JSON example

---

source/index.html.md

References https://github.com/denkungsart/filmmakers/issues/13041
- add `associations` to example

Add "associations" to TalentAgency example

---

source/index.html.md

References https://github.com/denkungsart/filmmakers/issues/13061
- add description about how to filter crew profiles by `professions` on index view

Describe crew professions filter

---

source/index.html.md

References https://github.com/denkungsart/filmmakers/issues/13124
- add web presences to JSON example

Add talent agency web presences

---

docs/actor-profiles.md
docs/changelog.md
docs/crew-profiles.md
docs/talent-agencies.md

References https://github.com/denkungsart/filmmakers/issues/13261
and PR https://github.com/denkungsart/filmmakers/pull/13276
- add `about_me` to JSON examples
- add explanation about locale

Add about_me/instagram/imdb for agency employees

---

docs/changelog.md
docs/talent-agencies.md

References https://github.com/denkungsart/filmmakers/issues/13270
- add `about_me` to JSON example
- add description of `about_me`

Add TalentAgency#about_me

---

docs/actor-profiles.md
docs/changelog.md

References https://github.com/denkungsart/filmmakers/issues/13285
- explain fallback to agency's categories
- add regions example and explain in attributes table

Regions in actor's agency connections
